package com.evry.fs.payment.pms.services.projectservice_v19_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-05-03T12:30:47.461+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/", name = "ProjectService_V19_1")
@XmlSeeAlso({com.evry.fs.payment.pms.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProjectServiceV191 {

    @WebMethod(action = "http://www.example.org/ProjectService_V19_1/addProject")
    @WebResult(name = "addProjectResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public com.evry.fs.payment.pms.AddProjectResponseType addProject(
        @WebParam(partName = "parameters", name = "addProjectRequestType", targetNamespace = "http://evry.com/fs/payment/pms")
        com.evry.fs.payment.pms.AddProjectRequestType parameters
    );

    @WebMethod(action = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/getProjectInfo")
    @WebResult(name = "getProjectInfoResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public com.evry.fs.payment.pms.GetProjectInfoResponseType getProjectInfo(
        @WebParam(partName = "parameters", name = "getProjectInfoRequestType", targetNamespace = "http://evry.com/fs/payment/pms")
        com.evry.fs.payment.pms.GetProjectInfoRequestType parameters
    );

    @WebMethod(action = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/updateProject")
    @WebResult(name = "updateProjectResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public com.evry.fs.payment.pms.UpdateProjectResponseType updateProject(
        @WebParam(partName = "parameters", name = "updateProjectRequestType", targetNamespace = "http://evry.com/fs/payment/pms")
        com.evry.fs.payment.pms.UpdateProjectRequestType parameters
    );

    @WebMethod(action = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/deleteProject")
    @WebResult(name = "deleteProjectResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public com.evry.fs.payment.pms.DeleteProjectResponseType deleteProject(
        @WebParam(partName = "parameters", name = "deleteProjectRequestType", targetNamespace = "http://evry.com/fs/payment/pms")
        com.evry.fs.payment.pms.DeleteProjectRequestType parameters
    );

    @WebMethod(action = "http://evry.com/fs/payment/pms/services/ProjectService_V19_1/getAllProjects")
    @WebResult(name = "getAllProjectsResponseType", targetNamespace = "http://evry.com/fs/payment/pms", partName = "parameters")
    public com.evry.fs.payment.pms.GetAllProjectsResponseType getAllProjects(
        @WebParam(partName = "parameters", name = "getAllProjectsRequestType", targetNamespace = "http://evry.com/fs/payment/pms")
        com.evry.fs.payment.pms.GetAllProjectsRequestType parameters
    );
}
