//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 07:37:54 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://evry.com/fs/payment/pms", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.evry.fs.payment.pms;
